### ISSUE TITLE
ChatVoicePlayer inside Recyclerview is laggy

### ISSUE THREAD

**Issue by ssfanist** [JagarYousef/ChatVoicePlayer#7]
I put the ChatVoicePlayer inside RecyclerView.ViewHolder and it is laggy.

**Comment by JagarYousef** [comment]
I will look into this, maybe because of the layouts it includes, and when there are too many of them loaded at the same time this could happen, it is recommended to limit the number of items (messages) loaded at the same time.

**Comment by crackyou** [comment]
Hello, I have an error when I link to an audio file from Firebase Storage. W / System.err: java.io.FileNotFoundException: https: /firebasestorage.googleapis.com/v0/b / ******* (No such file or directory)
W / System.err: at java.io.FileInputStream.open (Native Method)
         at java.io.FileInputStream. <init> (FileInputStream.java:146)
         at me.jagar.chatvoiceplayerlibrary.FileUtils.fileToBytes (FileUtils.java:14)
         at me.jagar.chatvoiceplayerlibrary.VoicePlayerView.setAudio (VoicePlayerView.java:211)
And this error makes RecyclerView lag when scrolling. Maybe that's the case?

**Comment by covenant3717** [comment]
Hi, can you tell me if there is any news on this issue?

**Comment by JagarYousef** [comment]
This should be fixed in the last update,
If it is still valid please feel free to reopen or open a new issue

**Comment by umer-sufyan** [comment]
This is still happening , it actually happened when you set audioPath to VoicePlayerView
